### ISSUE TITLE
Test improvements

### ISSUE THREAD

**Issue by natanlao** [ga4gh/data-object-service-schemas#133]
- [ ] `test_data_bundles` is too big and should be split into multiple tests
- [ ] Test data bundles and data objects have enough filler (`id`, `created`, etc.) that a helper function should be written to make code more concise

I think it's also worth considering updating the test suite to also use `requests` to call the API in addition to using the client since it's a standard use case that we don't yet test.

**Comment by david4096** [comment]
Great! The current test suite was written as a demo and reinterpreted as tests. It could be cleaned up by removing all the print statements, making more assertions about the contents of responses, test the error response surface, and be split up into a number of more shorter, named tests with some shared tear down.

The current tests would better be described as integration tests, since they test the bravado client and connexion server together.

To test at a lower level, suggest using the connexion app's test_client:

https://stackoverflow.com/questions/42934525/how-to-test-a-connexion-flask-app

Import `configure_app` from `server.py` and it will return an app you can write tests against without the  complexity of the bravado client.
