### ISSUE TITLE
Data bundles

### ISSUE THREAD

**Issue by david4096** [ga4gh/data-object-service-schemas#29]
In an effort to remove TODOs from the readme's I'm moving them to issues.

* do we want to use the [data bundles concept](https://docs.google.com/document/d/1d-9eu5X6ioOlqOJ9kkY8lHvXDF-KoynlmqJbuKVPMF0/edit#heading=h.b3jd47oqdd2e)? Often times we want to be able to model related files (like a workflow output) together in some way.  The data bundle concept supports this.
    * Data bundles are currently provided a rudimentary implementation. Needs review against HCA.

**Comment by mfiume** [comment]
Consider whether indices (e.g. .bam.bai) are implemented as bundles or if a DOS object should have an index pointer. Since indices are so common, the latter may (1) save hierarchical traversals through data bundles if one wants to find the associated index and (2) avoid guessing which element in a bundle is the index (e.g. by filename).

**Comment by david4096** [comment]
Thanks @mfiume ! You're right, having the ability to logically organize DataObjects without modifying underlying stores is useful.

In addition, Data Bundles are necessary as a first level of interaction with the DSS. https://github.com/DataBiosphere/dos-dss-lambda

Closing as Data Bundles are single level listings of DataObjects presented by the current API.
