### ISSUE TITLE
DEVELOP.md is out of date

### ISSUE THREAD

**Issue by david4096** [ga4gh/data-object-service-schemas#62]
Refers to an old project design that required a different build process.

**Comment by thejmazz** [comment]
Yes...my first attempts using only `pip install` were not enough, then I realized there was `setup.py`...

I have a WIP development environment using docker [here](https://github.com/thejmazz/data-object-service-schemas/tree/dockerize). At the moment it assumes development, but production would basically be the same except no volume mounts and probably a different command (unless k8s for production and then just leave `docker-compose.yml` assumed for dev). These days I try to develop *within* containers... it makes it easy to add a database via docker-compose later.

One issue for the volume mount for development (`-v $(pwd):/usr/src/app`), is that if the developer has not ran `python setup.py` on their host, then there will be no `./python/ga4gh/dos/data_object_server.swagger.yml`, and so the app startup fails: simple solution is to manually cp before `docker-compose up`. If this is rearranged then the docker based setup could be neater...but I don't want to make changes just for the sake of that (but it might be nice to not have a file which needs to be copied in sitting alongside main code). With node apps, I usually mount a `src` directory in alongside `node_modules` (in addition to individual `package.json` etc) so that deps can be used from a built container and a dev can work without needing to `npm install` on the host.

Also, is there any reason the OpenAPI spec is copied, rather than using a symlink?

If done well the develop instructions could basically be: `docker-compose up`.

Not sure how to get all the modules properly set up, for example, when I went to populate with demo data:

```
root@b3df8aa49a24:/usr/src/app# python python/examples/demo.py
Traceback (most recent call last):
  File "python/examples/demo.py", line 2, in <module>
    from ga4gh.dos.client import Client
  File "/usr/src/app/python/ga4gh/dos/__init__.py", line 1, in <module>
    import client
ModuleNotFoundError: No module named 'client'
root@b3df8aa49a24:/usr/src/app#
```

**Comment by david4096** [comment]
I am open to ways of improving the packaging of the schemas! I think it follows standard python patterns for development to need to run `python setup.py develop` to create required development artifacts, but its not a pattern that I find very intuitive and is best handled by an IDE. I wonder if symlinking would break the pypi packaging.

I'd like to get the development environment to where you imagine it, however, I should note that the server is not meant to be a "production" server. https://github.com/ohsu-comp-bio/dos_connect is a project that includes some containerization and work towards presenting a production DOS.

Regarding getting modules set up, again, try `python setup.py develop`.

One of the nice things about docker is you can handle that for a developer. I think the other option is adding the source directory to the python path, but I don't do that myself. Let me know if that works for you, happy to review any PRs that add dockerfiles :+1: !
